### ISSUE TITLE
Segmentation Fault on large directories

### ISSUE THREAD

**Issue by ACBob** [scaryrawr/sl#1]
When this is ran on a large directory (for example; `/bin`) it will chug along happily.
However, after a certain point (for me this was at J.) the train will crash, and cause a segmentation fault.

**Comment by scaryrawr** [comment]
I'm wondering if it's running low on memory? I tried running it in large directory (`/bin` on my machine) and it made it through. I have 16gb of ram though.

**Comment by ACBob** [comment]
That is a possibility, i only have 4gb of ram.

**Comment by scaryrawr** [comment]
If this still repros with the latest changes please re-open! it's kind of an assumption on why it's crashing.
