### ISSUE TITLE
Issues with flags

### ISSUE THREAD

**Issue by ACBob** [scaryrawr/sl#2]
I've merged both problems i found with the flags into one issue, for posterity.
When the train is small, (`-l`) there are no directories listed. I'm not sure if this was intentional, but it'd look nicer if the small train chugged along.
When the train is flying, (`-F`) Every carriage will follow along. This means, that after a few seconds, all of the carriages are off-screen, and you're staring at a blank screen for however long the train has left.

**Comment by scaryrawr** [comment]
Both of these should be fixed now (sorry for the wait!).

**Comment by ACBob** [comment]
Just tested it, both issues seem to have been fixed! :)
